<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class EditTelegramCommandValidationRequest extends FormRequest
{
    /**
     * Авторизован ли пользователь для выполнения этого запроса.
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Правила проверки, применимые к запросу.
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'command' => [
                'required',
                Rule::unique('telegram_commands', 'command')
                    ->ignore($this->route('telegramCommand'))
            ],
            'context' => 'required'
        ];
    }

    /**
     * Сообщение об ошибке на русском языке для полей
     * @return array|string[]
     */
    public function messages()
    {
        return parent::messages() + [
                'command.unique' => 'Команда :input уже существует',
                'command.required' => 'Поле обязательно для заполнения наименования',
                'context.required' => 'Поле обязательно для заполнения значения',
            ]; // TODO: Change the autogenerated stub
    }
}
