<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class LoginValidationRequest extends FormRequest
{
    /**
     * Определите, авторизован ли пользователь для выполнения этого запроса.
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Правила проверки, применимые к запросу.
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'login' => 'required',
            'password' => 'required'
        ];
    }

    /**
     * Сообщение об ошибке на русском языке для полей
     * @return array|string[]
     */
    public function messages()
    {
        return parent::messages() + [
                'login.required' => 'Поле обязательно для заполнения логина',
                'password.required' => 'Поле обязательно для заполнения пароля',
            ]; // TODO: Change the autogenerated stub
    }
}
